spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${custom.datasource.username}
    password: ${custom.datasource.password}
    url: jdbc:mariadb://${custom.datasource.masterUrl}:${custom.datasource.port}/${custom.datasource.databaseName}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    slaves:
      slave1:
        name: slave1
        driver-class-name: org.mariadb.jdbc.Driver
        username: ${custom.datasource.username}
        password: ${custom.datasource.password}
        url: jdbc:mariadb://${custom.datasource.slave1Url}:${custom.datasource.port}/${custom.datasource.databaseName}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: create
