spring:
  profiles:
    include: secret
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: create
logging:
  level:
    root: INFO
    com.ll.mariadbReplication2: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  base:
    package: com.ll.mariadbReplication2
    domainPackage: ${custom.base.package}.domain