spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
    url: jdbc:mariadb://localhost:3306/mariadbReplication2__dev
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create